remote_theme: pmarsceill/just-the-docs
logo: "assets/EICAA_Logo.png"
color_scheme: dark
has_toc: false

footer_content: "Copyright &copy; 2021-2023 <a href="https://adsata.com">Adsata</a> using <a href="https://just-the-docs.com/">Just the Docs</a>, a documentation theme for Jekyll."

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html
